spring:
  application:
    name: gugutask
  servlet:
    multipart:
      max-file-size: 5MB # 单个文件最大大小
      max-request-size: 5MB # 总请求大小

  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/gugutask?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.password}
  profiles:
    active: local

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 3006


